### PR TITLE
changes required to build for MultiTech mLinux conduit

### PR DESCRIPTION
**Pull request by kersing**
Made changes required to build for MultiTech mLinux conduit.

### CODE REVIEW

**Comment by devlaam** [comment]
Please accept my apologies for not yet accepting this pull request. The problem i have with the commit is that in the makefile patch we get a mixing of platform and spi device testing. This gets hairy very quickly, so an other solution is needed. Other small point; library.cfg should not be altered.

**Comment by kersing** [comment]
I understand your point regarding the Makefile, do you have any suggestions for a better solution? Using a different value for CFG_SPI would work but is equally ugly. (I would rather not have to modify the MultiTech supplied toolchain)

**Comment by devlaam** [comment]
Sorry for the long delay. I will look at this tomorrow. As more devices are appearing we need a 'clean' solution here.

**Comment by devlaam** [comment]
Sinde the number of contributions for different platforms in staggering, i decided to accept this solution for now, we can always change it when needed.

**Pull request merged**
